"""Building-block fragments for enumerating candidate NOM structures.

This module is a re-export facade. The implementation is split across:

* ``_fragment`` — :class:`MoleculeFragment`
* ``_fragment_data`` — ``FRAGMENT_LIBRARY`` / ``FUNCTIONAL_GROUPS``
* ``_factories`` — carbon-skeleton factory functions
* ``_functional`` — heteroatom / functional-group factory functions
"""

from ._fragment import MoleculeFragment
from ._fragment_data import FRAGMENT_LIBRARY, FUNCTIONAL_GROUPS

from ._factories import (
    create_methylene,
    create_ethylene,
    create_propylene,
    create_alkene,
    create_propenyl,
    create_alkyne,
    create_propynyl,
    create_cyclopentane,
    create_cyclopentene,
    create_cyclopentadiene,
    create_cyclohexane,
    create_cyclohexene,
    create_cyclohexadiene,
    create_benzene,
    create_cyclooctane,
    create_cyclooctene,
    create_cyclooctadiene,
    create_cyclooctatriene,
    create_cyclooctatetraene,
    create_cyclodecane,
    create_cyclodecene,
    create_cyclodecadiene,
    create_cyclodecatriene,
    create_cyclodecatetraene,
    create_cyclodecapentaene,
    create_naphthalene,
    create_anthracene,
)

from ._functional import (
    create_pyrrolidine,
    create_pyrroline,
    create_pyrrole,
    create_imidazole,
    create_tetrahydrofuran,
    create_dihydrofuran,
    create_furan,
    create_piperidine,
    create_tetrahydropyridine,
    create_dihydropyridine,
    create_pyridine,
    create_pyrimidine,
    create_pyrazine,
    create_tetrahydropyran,
    create_dihydropyran,
    create_cooh,
    create_oh,
    create_cho,
    create_co,
    create_coo,
    create_o_ether,
    create_nh2,
    create_nh,
    create_n_tertiary,
    create_no2,
    create_cn,
    create_conh2,
    create_sh,
    create_s_sulfide,
    create_so2,
    create_so3h,
    create_f,
    create_cl,
    create_br,
    create_i,
    create_aminomethyl,
    create_amide_link,
    create_ethylamine,
)

# Словарь всех фабричных функций
ALL_FRAGMENTS = {
    "methylene": create_methylene,
    # "ethylene": create_ethylene,
    # "propylene": create_propylene,
    "alkene": create_alkene,
    "propenyl": create_propenyl,
    # "alkyne": create_alkyne,
    # "propynyl": create_propynyl,
    "cyclopentane": create_cyclopentane,
    "cyclopentene": create_cyclopentene,
    "cyclopentadiene": create_cyclopentadiene,
    "cyclohexane": create_cyclohexane,
    "cyclohexene": create_cyclohexene,
    "cyclohexadiene": create_cyclohexadiene,
    "benzene": create_benzene,
    # "cyclooctane": create_cyclooctane,
    # "cyclooctene": create_cyclooctene,
    # "cyclooctadiene": create_cyclooctadiene,
    # "cyclooctatriene": create_cyclooctatriene,
    # "cyclooctatetraene": create_cyclooctatetraene,
    # "cyclodecane": create_cyclodecane,
    # "cyclodecene": create_cyclodecene,
    # "cyclodecadiene": create_cyclodecadiene,
    # "cyclodecatriene": create_cyclodecatriene,
    # "cyclodecatetraene": create_cyclodecatetraene,
    # "cyclodecapentaene": create_cyclodecapentaene,
    "naphthalene": create_naphthalene,
    "anthracene": create_anthracene,
    "pyrrolidine": create_pyrrolidine,
    "pyrroline": create_pyrroline,
    "pyrrole": create_pyrrole,
    "imidazole": create_imidazole,
    "tetrahydrofuran": create_tetrahydrofuran,
    "dihydrofuran": create_dihydrofuran,
    "furan": create_furan,
    "piperidine": create_piperidine,
    "tetrahydropyridine": create_tetrahydropyridine,
    "dihydropyridine": create_dihydropyridine,
    "pyridine": create_pyridine,
    "pyrimidine": create_pyrimidine,
    "pyrazine": create_pyrazine,
    "tetrahydropyran": create_tetrahydropyran,
    "dihydropyran": create_dihydropyran,
    "aminomethyl": create_aminomethyl,
    "amide_link": create_amide_link,
    "ethylamine": create_ethylamine,
    "cooh": create_cooh,
    "oh": create_oh,
    "cho": create_cho,
    "co": create_co,
    "coo": create_coo,
    "o_ether": create_o_ether,
    "nh2": create_nh2,
    "nh": create_nh,
    "n_tertiary": create_n_tertiary,
    "no2": create_no2,
    "cn": create_cn,
    "conh2": create_conh2,
    "sh": create_sh,
    "s_sulfide": create_s_sulfide,
    "so2": create_so2,
    "so3h": create_so3h,
    # "f": create_f,
    # "cl": create_cl,
    # "br": create_br,
    # "i": create_i,
}
